### ISSUE TITLE
Preact

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/newalkalisite#25]
@ogdenstudios

I was doing some reading and saw the suggestion of using Preact if I'm not using any advanced react components, is this something you would recommend?

**Comment by ogdenstudios** [comment]
Huh, interesting. I've never written Preact, but I've read about it and listened to some of the maintainers on podcasts. I'm aware of the project and think it's cool. 

My initial reaction was "no", because I thought Next.js relied on React specifically for SSR, and you'd have to migrate a bunch of stuff over. But it looks like you can do SSR with Preact, too. 

I know you're hyper aware of the performance of the site. And overall, I think your use case of React is simple enough that Preact would meet your needs. So tentatively, Preact might be a good choice for you. 

But if it was me, I wouldn't do it. Right now Preact says it has 100% compatibility with React. But how do we know it always will? I mean, it probably will, but maybe more realistically - what if you one day want to use React's advanced features? Migration could be a headache. 

Or, if you brought in a React developer here, they could probably figure it out plenty fine, but there's going to be some differential between the two. Especially since you've got a Next.js project. To me, that clearly says "Hey this is in React". And if I found out it was Preact, I would be a little shocked. 

Also I think there's lots of brand recognition behind React, both for your own skills, and for hiring developers and collaborators. 

All that to say, I don't have a strong recommendation for you. You'd probably get some performance gains here, they might be significant enough to be worth it. It could also come with headaches down the road. And again, if it were me, I probably wouldn't do it, but only because of my own biases, and not for any other good objective reason. 

Wish I had a stronger answer for you, but tech stack questions like this are sometimes the most ambiguous, because the answer is not only "it depends", but also "what do you want?" and "what do you prefer?" and a bunch of other personal decision making stuff. 

Preact is a totally valid migration here, you probably wouldn't notice the rough edges of the migration. But I wouldn't embark on it of my own volition, haha. Wish I could give you a better answer!

**Comment by baudoinalkali** [comment]
@ogdenstudios I could be totally wrong, but it seems like it's as simple as adding a few lines to the next.config.js file and the only potential is it breaks something, but then it can be removed. Link for reference:

https://dev.to/dlw/next-js-replace-react-with-preact-2i72

**Comment by baudoinalkali** [comment]
Disregard, I tried that last night and there was 0 difference to the build sizes.

**Comment by ogdenstudios** [comment]
Yeah, that looks about right. You'll also have to make sure you use [preact-compat](https://github.com/developit/preact-compat) for using React children, which is mostly what I was getting at - if you switch to Preact, you might end up having to do a bunch of specific configuration, and it might not be "conventional". 

For something like this, it's certainly worth it to try it and then revert the changes if the gains don't seem to be worth it.

**Comment by ogdenstudios** [comment]
Oh, haha well there you go. Glad you tried it out to see!
