### ISSUE TITLE
Advice on Array Situation

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/newalkalisite#48]
@ogdenstudios

I started breaking down parts of the single client page to be more reusable. An obvious candidate was the hero section. Everything seems like it would be straightforward except for one part. I thought it would be best to have a data file specifically for headers. I added an example [here](https://github.com/baudoinalkali/newalkalisite/blob/c567219846dd9462c438533bc8f8ae3329c49ff1/content/clientPages/clientHeroContent.ts#L7). My question pertains to the service property. If a client could have several services rendered how would I go about dumbing the array contents into [this component](https://github.com/baudoinalkali/newalkalisite/blob/c567219846dd9462c438533bc8f8ae3329c49ff1/components/ClientHeader.tsx#L14). Currently it adds the data correct, just not separated in their own container. I'm unsure how to do this to get each array element into it's own <li> tag so that I could add a flex class and have them displayed side by side. I tried a  few split variations but kept getting errors.

**Comment by ogdenstudios** [comment]
Since `props.service` is just an array, you can do something like this: 

```js
{props.service.map(service => <span key={service}>{service}</span>)}
```

I wonder if the errors you were getting were because you had [neglected to add the key attribute to your JSX list items](https://reactjs.org/docs/lists-and-keys.html#keys), which I've added in this example. 

Let me know if that doesn't work, and I can dig deeper for you. But I think this is what you're looking for.
