### ISSUE TITLE
Image Component Angle Issue

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/newalkalisite#73]
@ogdenstudios

I noticed this awhile ago when I made the switch to the Next Image component. It seems the Image component automatically applies overflow hidden to the images. Is there a way to selectively override this? 
![image](https://user-images.githubusercontent.com/79876365/115898824-9b39d000-a423-11eb-815c-8b2acae6e0c3.png)

**Comment by ogdenstudios** [comment]
Hey @baudoinalkali - I am a little wiped out this evening. I'll get to this over the weekend.

**Comment by ogdenstudios** [comment]
Hey @baudoinalkali - I don't think there's a way to disable this behavior. 

[This GitHub issue has a bunch of people running into the same problems](https://github.com/vercel/next.js/issues/18585). It looks like the conventional way of doing everything here is with [a bunch of wrapper divs](https://github.com/vercel/next.js/issues/18585#issuecomment-788081710). 

Also, it looks like the CLS problem in #72 [is related to this very same thing](https://github.com/vercel/next.js/issues/18585#issuecomment-792291602). 

If it were me, I might consider not using the Next image component at all at this point: managing the wrapper classes, dealing with the CLS, and not having the option to fully customize it all.

If you want to get the lazy loading and performance benefits, you might look into [using native lazy loading](https://web.dev/browser-level-image-lazy-loading/) and then using something like [Cloudinary image optimization](https://cloudinary.com/documentation/image_optimization) - that way you could use the native `img` elements and get more fine-grained control on everything. 

I think it comes down to this tradeoff: 

1. Using the Next image component gets you some up front performance improvements you don't have to think about. But you're locked in to their configuration options, and any bugs/issues they ship are yours to deal with as well. Still, it's a quick tool to use. 
1. Writing your own image optimization requires digging into the performance concerns under the hood. You'll have to deal with the browser-level and CDN-level optimization. It's more work up front, but it gives you more control over your own images and their customization. The added benefit is that you then don't have to rely on Next to fix bugs (but of course, _you_ will have to fix your bugs, haha). 

So the short answer to this specific issue is: I don't think you can turn off `overflow: hidden`. You should use additional wrapper styles around the image instead.

The longer answer is: maybe this + the cumulative layout shift issues are good reasons to consider writing images natively instead, but that's a bigger change to make.

**Comment by baudoinalkali** [comment]
@ogdenstudios I looked into the issue for a few hours as well before bringing it up and saw the same issues mentioned. I don't think the Image component is causing the CLS, because gtmetrix.com outlines what is affecting the CLS and it doesn't seem to be showing any elements relating to the Image component. I'll run more reports though to make sure. I'm not opposed to doing something more custom, native lazy loading seems to be very straightforward. The one question mark I had about Cloudinary is that it says you have a 25k transformation per month limit for the free plan, which I interpret to be every image is transformed for each user request, so given my current traffic I would need to use the $99/mo plan. With that said it seems like the only downside is this one use case (and possibly the CLS). I'll try to think about it and see if it would just make more sense to transform the images before uploading them.

**Comment by ogdenstudios** [comment]
Gotcha. 

I ran https://newalkalisite.vercel.app/services/web-development/wordpress-website-development through gtmetrix.com and I _do_ think the WordPress image is contributing to a little bit: 

<img width="873" alt="Screen Shot 2021-04-24 at 4 48 18 PM" src="https://user-images.githubusercontent.com/29899554/115974841-ea176080-a51c-11eb-83d4-eff482b35754.png">

But looks like it's minor, so it doesn't jump out at me as a huge deal either way.

I think overall this is the answer: 

>  I'll try to think about it and see if it would just make more sense to transform the images before uploading them.

The CLS is minor (if it exists at all). The overflow limitation is annoying, but you'll probably be able to solve it just by making the source imagery closer to its intended final form. 

As for Cloudinary, that makes sense. I don't use it for any of my personal sites, but we are exploring a migration to it at work. I don't know the specifics of their pricing, but you could also look into something like [Cloudflare](https://www.cloudflare.com/cdn/) or [Fastly](https://www.fastly.com/) as well. 

I guess the thing I'm really trying to get at is that using any external CDN solution, you might be able to achieve the Next image effect without having to mess with the Next image component, and I personally lean towards using native markup like `img` tags or `figure` tags over the Next image component, or things like Gatsby's image components. There's just some solutions out there that achieve the same thing but give you more control. But since the CLS is either minor, or perhaps mis-diagnosed (and is coming from elsewhere), I don't feel super strongly in this case. 

Let me know if you want me to dive deeper into the CLS stuff. If it isn't the Next image component, then I'd have to spend a few hours digging in.
